### ISSUE TITLE
Package server returning 404

### ISSUE THREAD

**Issue by RRvW** [mumble-voip/grumble#32] opened 2018-09-23 21:04 UTC
Hi, I'm trying to build grumble, but everything under [mumble.info/grumble](https://mumble.info/grumble) returns a 404 request. Using Go 1.10:
```
Fetching https://mumble.info/grumble/cmd/grumble?go-get=1
Parsing meta tags from https://mumble.info/grumble/cmd/grumble?go-get=1 (status code 404)
package mumble.info/grumble/cmd/grumble: unrecognized import path "mumble.info/grumble/cmd/grumble" (parse https://mumble.info/grumble/cmd/grumble?go-get=1: no go-import meta tags ())
```
Same situation for all packages when building Grumble from source

**Comment by kroppt** [comment] 2019-05-11 18:49
Workaround:
```bash
$ git clone git clone git@github.com:mumble-voip/grumble.git
$ cd grumble
$ grep --include=*.go -rl '.' | xargs sed -i -- 's/mumble.info\/grumble/github.com\/mumble-voip\/grumble/g'
$ go mod init
$ go install ...
```

This replaces all instances of `mumble.info/grumble` with `github.com/mumble-voip/grumble` in source files. It will also build and install to your standard Go bin directory.

To get it to work, I also had to run:
```bash
$ mkdir ~/.grumble
$ sudo setcap CAP_NET_BIND_SERVICE=+eip /path/to/grumble
```

Then running `grumble` worked.

**Comment by olabiniV2** [comment] 2019-12-20 23:03
#41 is a duplicate of this

**Comment by davidebeatrici** [comment] 2019-12-20 23:08
Superseded by #41.

**Closed by davidebeatrici** 2019-12-20 23:08 UTC
