### ISSUE TITLE
Unusable - Can't create channels

### ISSUE THREAD

**Issue by cyisfor** [mumble-voip/grumble#40] opened 2019-10-09 05:41 UTC
Only the super user SuperUser can create a channel, but the code to set the password for SuperUser over ssh was removed, and the code to use an RPC interface called Dial to set the password was also removed, leaving no code anywhere ever giving SuperUser a password. Trying to log in with an empty password does not work.

Thus, unless I'm totally misunderstanding, no one can create channels under any circumstances.  That means all you can do is connect to the server, which has no channels, and just kind of sit there staring at it, imagining it actually doing something. If this is just supposed to be a toy application, at least having some code that said `something.server.SetSuperuserPassword("thisisonlyatoydonotuse")` would be nice. Otherwise, far as I can tell, it's totally unusable.

**Comment by davidebeatrici** [comment] 2019-10-09 05:44
Duplicate of #20.

**Closed by davidebeatrici** 2019-10-09 05:44 UTC

**Comment by cyisfor** [comment] 2019-10-09 07:39
yeah, sorry. Didn't see that one.

**Comment by davidebeatrici** [comment] 2019-10-09 08:13
No worries!
